### ISSUE TITLE
BUG - Plugin throws error on redmine 2.5.2

### ISSUE THREAD

**Issue by stb** [Enkil/redmine_reminder#19]
```
Started GET "/my/account" for 127.0.0.1 at 2014-08-21 09:52:09 +0200
Processing by MyController#account as HTML
  Current user: xxx@xxx.xxx (id=5)
  Rendered my/account.html.erb within layouts/base (13.3ms)
Completed 500 Internal Server Error in 22.4ms

ActionView::Template::Error (undefined method `plugin_redmine_reminder' for #<Class:0x007fcdbedf74e0>):
    26:   <% @user.custom_field_values.select(&:editable?).each do |value| %>
    27:     <p><%= custom_field_tag_with_label :user, value %></p>
    28:   <% end %>
    29:   <%= call_hook(:view_my_account, :user => @user, :form => f) %>
    30: </fieldset>
    31:
    32: <%= submit_tag l(:button_save) %>
  lib/redmine/hook.rb:61:in `block (2 levels) in call_hook'
  lib/redmine/hook.rb:61:in `each'
  lib/redmine/hook.rb:61:in `block in call_hook'
  lib/redmine/hook.rb:58:in `tap'
  lib/redmine/hook.rb:58:in `call_hook'
  lib/redmine/hook.rb:158:in `call_hook'
  app/views/my/account.html.erb:29:in `block in _app_views_my_account_html_erb___1115250790936681840_70260847919040'
  app/helpers/application_helper.rb:1043:in `labelled_form_for'
  app/views/my/account.html.erb:9:in `_app_views_my_account_html_erb___1115250790936681840_70260847919040'
```

**Comment by f0y** [comment]
Are you sure that it is not related to your redmine installation?
