### ISSUE TITLE
error when trying to send notifications

### ISSUE THREAD

**Issue by dan-omniscience** [Enkil/redmine_reminder#4]
Hello,
I installed your plugin and came across few problems
1) is the same as reported about save of my account settings
2) is when I tried to initiate the send notification command in shell, this is the error I received
bundle exec rake redmine:reminder_plugin:send_notifications RAILS_ENV=production --trace
*\* Invoke redmine:reminder_plugin:send_notifications (first_time)
*\* Invoke environment (first_time)
*\* Execute environment
*\* Execute redmine:reminder_plugin:send_notifications
rake aborted!
uninitialized constant ReminderMailer
{redmine}/plugins/redmine_reminder/lib/tasks/reminder.rake:5
{redmine}/app/models/mailer.rb:377:in `with_synched_deliveries'
{redmine}/plugins/redmine_reminder/lib/tasks/reminder.rake:4
/usr/local/lib/ruby/gems/1.8/gems/rake-10.0.4/lib/rake/task.rb:246:in`call'
/usr/local/lib/ruby/gems/1.8/gems/rake-10.0.4/lib/rake/task.rb:246:in `execute'
/usr/local/lib/ruby/gems/1.8/gems/rake-10.0.4/lib/rake/task.rb:241:in`each'
/usr/local/lib/ruby/gems/1.8/gems/rake-10.0.4/lib/rake/task.rb:241:in `execute'
/usr/local/lib/ruby/gems/1.8/gems/rake-10.0.4/lib/rake/task.rb:184:in`invoke_with_call_chain'
/usr/local/lib/ruby/1.8/monitor.rb:242:in `synchronize'
/usr/local/lib/ruby/gems/1.8/gems/rake-10.0.4/lib/rake/task.rb:177:in`invoke_with_call_chain'
/usr/local/lib/ruby/gems/1.8/gems/rake-10.0.4/lib/rake/task.rb:170:in `invoke'
/usr/local/lib/ruby/gems/1.8/gems/rake-10.0.4/lib/rake/application.rb:143:in`invoke_task'
/usr/local/lib/ruby/gems/1.8/gems/rake-10.0.4/lib/rake/application.rb:101:in `top_level'
/usr/local/lib/ruby/gems/1.8/gems/rake-10.0.4/lib/rake/application.rb:101:in`each'
/usr/local/lib/ruby/gems/1.8/gems/rake-10.0.4/lib/rake/application.rb:101:in `top_level'
/usr/local/lib/ruby/gems/1.8/gems/rake-10.0.4/lib/rake/application.rb:110:in`run_with_threads'
/usr/local/lib/ruby/gems/1.8/gems/rake-10.0.4/lib/rake/application.rb:95:in `top_level'
/usr/local/lib/ruby/gems/1.8/gems/rake-10.0.4/lib/rake/application.rb:73:in`run'
/usr/local/lib/ruby/gems/1.8/gems/rake-10.0.4/lib/rake/application.rb:160:in `standard_exception_handling'
/usr/local/lib/ruby/gems/1.8/gems/rake-10.0.4/lib/rake/application.rb:70:in`run'
/usr/local/lib/ruby/gems/1.8/gems/rake-10.0.4/bin/rake:33
/usr/local/bin/rake:19:in `load'
/usr/local/bin/rake:19
Tasks: TOP => redmine:reminder_plugin:send_notifications

**Comment by Enkil** [comment]
Hi,
maybe it was because repo-name was not correct #3 
Please, try to reinstall plugin and say how it will be work

On clean redmine install it works correctly

**Comment by dan-omniscience** [comment]
this not seem related to my situation, I have the latest plugin from the
git...

On Thu, Jun 13, 2013 at 3:26 PM, Igor Timohin notifications@github.comwrote:

> Hi,
> maybe it was because repo-name was not correct #3https://github.com/Enkil/redmine_reminder/issues/3
> Please, try to reinstall plugin and say how it will be work
> 
> On clean redmine install it works correctly
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/Enkil/redmine_reminder/issues/4#issuecomment-19388243
> .

## 

Dan Aharon-Shalom
_Omniscience, Software & Web Application Development_
Barkan 27 P.O.B 182
Lehavim 85338
Israel
Ph: +972 545917781
Email: dan@omnisciene.co.il
http://www.omniscience.co.il

**Comment by Enkil** [comment]
repo-name was changed just for an hour ago, and redmine can has problems with okd dir-name (which is based on repo-bame)
Please, try to reinstall
