### ISSUE TITLE
send_notification aborted (different error)

### ISSUE THREAD

**Issue by stf675** [Enkil/redmine_reminder#7]
I can configure and save plugin settings, but when I run

bundle exec rake redmine:reminder_plugin:send_notifications RAILS_ENV=production --trace

I end up with:

'''*\* Invoke redmine:reminder_plugin:send_notifications (first_time)
*\* Invoke environment (first_time)
*\* Execute environment
*\* Execute redmine:reminder_plugin:send_notifications
rake aborted!
undefined method `reminder_notification_array' for #<Group:0x3189108>
C:/BitNami/redmine/ruby/lib/ruby/gems/1.9.1/gems/activemodel-3.2.9/lib/active_model/attribute_methods.rb:407:in`method_missing'
C:/BitNami/redmine/ruby/lib/ruby/gems/1.9.1/gems/activerecord-3.2.9/lib/active_record/attribute_methods.rb:149:in `method_missing'
C:/BitNami/redmine/apps/redmine/htdocs/plugins/due_date_reminder/lib/reminder/issue_patch.rb:18:in`remind?'
C:/BitNami/redmine/apps/redmine/htdocs/plugins/due_date_reminder/app/models/reminder_mailer.rb:42:in `block in find_issues'
C:/BitNami/redmine/apps/redmine/htdocs/plugins/due_date_reminder/app/models/reminder_mailer.rb:42:in`reject!'
C:/BitNami/redmine/apps/redmine/htdocs/plugins/due_date_reminder/app/models/reminder_mailer.rb:42:in `find_issues'
C:/BitNami/redmine/apps/redmine/htdocs/plugins/due_date_reminder/app/models/reminder_mailer.rb:15:in`due_date_notifications'
C:/BitNami/redmine/apps/redmine/htdocs/plugins/due_date_reminder/lib/tasks/reminder.rake:5:in `block (4 levels) in <top (required)>'
C:/BitNami/redmine/apps/redmine/htdocs/app/models/mailer.rb:377:in`with_synched_deliveries'
C:/BitNami/redmine/apps/redmine/htdocs/plugins/due_date_reminder/lib/tasks/reminder.rake:4:in `block (3 levels) in <top (required)>'
C:/BitNami/redmine/ruby/lib/ruby/gems/1.9.1/gems/rake-0.9.2.2/lib/rake/task.rb:205:in`call'
C:/BitNami/redmine/ruby/lib/ruby/gems/1.9.1/gems/rake-0.9.2.2/lib/rake/task.rb:205:in `block in execute'
C:/BitNami/redmine/ruby/lib/ruby/gems/1.9.1/gems/rake-0.9.2.2/lib/rake/task.rb:200:in`each'
C:/BitNami/redmine/ruby/lib/ruby/gems/1.9.1/gems/rake-0.9.2.2/lib/rake/task.rb:200:in `execute'
C:/BitNami/redmine/ruby/lib/ruby/gems/1.9.1/gems/rake-0.9.2.2/lib/rake/task.rb:158:in`block in invoke_with_call_chain'
C:/BitNami/redmine/ruby/lib/ruby/1.9.1/monitor.rb:211:in `mon_synchronize'C:/BitNami/redmine/ruby/lib/ruby/gems/1.9.1/gems/rake-0.9.2.2/lib/rake/task.rb:151:in`invoke_with_call_chain'
C:/BitNami/redmine/ruby/lib/ruby/gems/1.9.1/gems/rake-0.9.2.2/lib/rake/task.rb:144:in `invoke'
C:/BitNami/redmine/ruby/lib/ruby/gems/1.9.1/gems/rake-0.9.2.2/lib/rake/application.rb:116:in`invoke_task'
C:/BitNami/redmine/ruby/lib/ruby/gems/1.9.1/gems/rake-0.9.2.2/lib/rake/application.rb:94:in `block (2 levels) in top_level'
C:/BitNami/redmine/ruby/lib/ruby/gems/1.9.1/gems/rake-0.9.2.2/lib/rake/application.rb:94:in`each'
C:/BitNami/redmine/ruby/lib/ruby/gems/1.9.1/gems/rake-0.9.2.2/lib/rake/application.rb:94:in `block in top_level'
C:/BitNami/redmine/ruby/lib/ruby/gems/1.9.1/gems/rake-0.9.2.2/lib/rake/application.rb:133:in`standard_exception_handling'
C:/BitNami/redmine/ruby/lib/ruby/gems/1.9.1/gems/rake-0.9.2.2/lib/rake/application.rb:88:in `top_level'
C:/BitNami/redmine/ruby/lib/ruby/gems/1.9.1/gems/rake-0.9.2.2/lib/rake/application.rb:66:in`block in run'
C:/BitNami/redmine/ruby/lib/ruby/gems/1.9.1/gems/rake-0.9.2.2/lib/rake/application.rb:133:in `standard_exception_handling'
C:/BitNami/redmine/ruby/lib/ruby/gems/1.9.1/gems/rake-0.9.2.2/lib/rake/application.rb:63:in`run'
C:/BitNami/redmine/ruby/lib/ruby/gems/1.9.1/gems/rake-0.9.2.2/bin/rake:33:in `<top (required)>'
C:/BitNami/redmine/ruby/bin/rake:23:in`load'
C:/BitNami/redmine/ruby/bin/rake:23:in `<main>'
Tasks: TOP => redmine:reminder_plugin:send_notifications'''

What do i miss?

**Comment by stf675** [comment]
upgraded to RM 2.3.2

same error:

rake aborted!
undefined method reminder_notification_array' for #Group:0xxxxxxxx

do I missing something on post install configuration?

what do 1,3,5 mean in configuration: 1st, 2nd, 5th day of the week or 1, 3, 5 days left?

are categories  required, and do I need to apply it to all issues?

please advise.

**Comment by Enkil** [comment]
1,3,5, etc - means for the number of days left to end of task and in this days plugin will send notification via email

about error - did you designate group to task, not a user?

**Comment by stf675** [comment]
I changed due date to 1 day ahead (thought it was supposed to be overdue), task assigned to me as single user, no watchers.

same error.

I was using existing task for a test

**Comment by claudiomoscoso** [comment]
I saw that the error occurs when I assign issues to a group. someone has a solution for this error?

**Comment by jeangnc** [comment]
same error here

**Comment by jeangnc** [comment]
anyone have a solution?

**Comment by cuggen** [comment]
I have this same issue.  It is definitely when a group is assigned to an issue with a due date.  Is there a work around?

**Comment by pydubreucq** [comment]
+1
I have assigned a task to a group too.
Bye
